import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <head>
        {process.env.NEXT_PUBLIC_TRANSLATOR_TOKEN && (
          <meta httpEquiv="origin-trial" content={process.env.NEXT_PUBLIC_TRANSLATOR_TOKEN} />
        )}
        {process.env.NEXT_PUBLIC_DETECTOR_TOKEN && (
          <meta httpEquiv="origin-trial" content={process.env.NEXT_PUBLIC_DETECTOR_TOKEN} />
        )}
        {process.env.NEXT_PUBLIC_SUMMARIZER_TOKEN && (
          <meta httpEquiv="origin-trial" content={process.env.NEXT_PUBLIC_SUMMARIZER_TOKEN} />
        )}
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
